title: My socials 
theme: minima
author: Thomas Jaycard
email: Trexking901@icloud.com
description: My socials 



# social links
github_username:  Tjaycard # DO NOT include the @ character, or else the build will fail!
instagram_username: thomas_jaycard2

show_excerpts: true # set to false to remove excerpts on the homepage
