title: Thomas Jaycard 
theme: minima
author: My socials are
author: My phone number is 732-619-3571
email: Trexking901@icloud.com
phone_number: 732-619-3571



# social links
github_username:  Tjaycard # DO NOT include the @ character, or else the build will fail!
instagram_username: thomas_jaycard2

show_excerpts: true # set to false to remove excerpts on the homepage
